%%
%Lab 2
%Valery Smith and Christopher Caldwell
%%
% Signal:
%clc
close all
clear

v=4;

t = (0:255)/256;
x = cos(2*pi*5*t)>0;

%%
% Filter:

h = ones(1,12)/12;

%plot of x and h and x*h

y=conv(x,h);

figure(1);

subplot(v,1,1);
plot(t, x);
ylabel("Amplitude")
xlabel("Time")
title("Graph of Signal 'x'")

subplot(v,1,2);
plot((0:length(y)-1)/length(t), y);
ylabel("Amplitude")
xlabel("Time")
title("Graph of Signal 'x*h'")

%%


%M         M-samples for FIR Filter
%L         Data Sequence Length
Q=64; %    Length of Blocks
%K = L/Q   Number of short blocks, length Q

%xk = reshape(x, Q, K)'; % creating matrix.

xk = reshape(x, 64, 4)';

lf = 256+12-1;
yb = zeros(1,lf);
lb = 64+12-1;

ya1 = conv(xk(1,:),h);
ya2 = conv(xk(2,:),h);
ya3 = conv(xk(3,:),h);
ya4 = conv(xk(4,:),h);


%d=64;

yb(1:75) = yb(1:75) + ya1;
yb(65:139)= yb(65:139) + ya2;
yb(129:129+74)= yb(129:129+74) + ya3;
yb(193:193+74)= yb(193:193+74) + ya4;
%yb(128:204)= yb(128:204) + conv(xk(4,:),h);
%yb(192:268)= yb(192:268) + conv(xk(

%n=0, 1->76   1->76    1->76
%n=1, 13->89  77->153  64->140
%n=2, 25->101 154->230 128->204
%n=3, 37->113 231->307 192->268




subplot(v,1,3);
plot((0:length(yb)-1)/length(t), yb, '--' );
ylabel("Amplitude")
xlabel("Time")
title("Graph of Signal 'yb'")

yb_by_func = overlap_add(h, x, Q);

subplot(v,1,4);

plot((0:length(yb_by_func)-1)/length(t), yb_by_func);
ylabel("Amplitude")
xlabel("Time")
title("Graph of Signal 'yb' Generated by Function")
%%
t = (0:8191)/8192;
x1 = cos(2*pi*4096*(t.*t));
%sound(x1);

M=9;

figure(2);

h = hamming(M);
h=h'/sum(h);
stem(h);
ylabel("Amplitude")
xlabel("Time")
title("Graph of hann window filter :)")

y=overlap_add(h,x1,256);
%sound(y); 

yn = y(1:length(t));
figure(3);
plot(t*8192,abs(yn));
ylabel("Amplitude")
xlabel("Time")
title("Graph of absolute value of filtered with hann window")

for n=1:9;
h1(n)=h(n)*((-1)^n);
end

figure(4)
stem(h1)

yp=overlap_add(h1,x1,256);
sound(yp); 

figure(5);
plot(1:length(yp),abs(yp));
ylabel("Amplitude")
xlabel("Time")
title("Graph of Filtered Chirp")

testa=fft(h1);
figure(6);
plot(abs(real(testa)));


